# Generated by Django 3.1.3 on 2021-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='is_user_active',
            field=models.CharField(blank=True, choices=[('DEACTIVATE', 'Deactivate'), ('ACTIVATE', 'Activate')], default='ACTIVATE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='editorspick',
            name='editor_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=200, null=True),
        ),
    ]
