# Generated by Django 3.1.3 on 2021-03-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogbackapp', '0002_auto_20210318_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogger',
            name='group_status',
            field=models.CharField(blank=True, choices=[('BLOGGER', 'Blogger'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=200, null=True),
        ),
    ]
